welcome:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
      template: login/welcomePage.html.twig
login:
  path: /login
  controller: App\Controller\SecurityController::login_check
checkBeforeRoom:
  path: /checkBeforeRoom
  controller: App\Controller\SecurityController::checkBeforeRoom
index:
  path: /index
  controller: App\Controller\SecurityController::index
new_room:
  path: /newRoom
  controller: App\Controller\SecurityController::newRoom
join_room:
  path: /joinRoom
  controller: App\Controller\SecurityController::joinRoom
rememberPassword:
  path: /rememberPassword
  controller: App\Controller\SecurityController::rememberPassword