welcome:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
      template: login/welcomePage.html.twig
login:
  path: /login
  controller: App\Controller\SecurityController::login_check
checkBeforeRoom:
  path: /checkBeforeRoom
  controller: App\Controller\SecurityController::checkBeforeRoom
newRoom:
  path: /newRoom
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: login/newRoom.html.twig
joinRoom:
  path: /joinRoom
  controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
  defaults:
    template: login/joinRoom.html.twig
index:
  path: /index
  controller: App\Controller\SecurityController::index
rememberPassword:
  path: /rememberPassword
  controller: App\Controller\SecurityController::rememberPassword