login:
    path: /
    controller: Symfony\Bundle\FrameworkBundle\Controller\TemplateController::templateAction
    defaults:
      template: login/welcomePage.html.twig
login_check:
  path: /login
  controller: App\Controller\LoginController::login_check
checkBeforeRoom:
  path: /checkBeforeRoom/{where}
  controller: App\Controller\LoginController::checkBeforeRoom
new_room:
  path: /newRoom
  controller: App\Controller\LoginController::newRoom
join_room:
  path: /joinRoom
  controller: App\Controller\LoginController::joinRoom